# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8bf56e2f75c96a192be9760899735dc08c88c050c51e7ad252ee201f233c7c781919be5d7b4f3b942d57fae9744a0364b516f0072b72e4bcb27f464068a96c0

test:
  secret_key_base: 87c2d5d41c2642c19d3739f90e27a1e7cd331d25230067b94b155e6ad99242fbf625f84669fee32d27c42192707bfd86cf3252e606e3d23e71ea8e2d762190c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
